### ISSUE TITLE
Cannot compile on Ubuntu 14.04 (wrong include path in wscript?)

### ISSUE THREAD

**Issue by pylaterreur** [Vladec/matching-engine#1]
Using current master (e5f54a975fc0646abba19a9e6ed502640a43a1e0).

When I try to compile, a header file (my_global.h) is not found.

It actually is stored at /usr/include/mysql/my_global.h (and not somewhere like /export/mariadb/include, which is a path that doesn't exist on my Linux).

``` terminal
$> ./waf-1.7.15/waf configure build
Setting top to                           : /home/pyro/c++/matching-engine 
Setting out to                           : /home/pyro/c++/matching-engine/build 
Checking for waf version in 1.7.5-1.8.0  : ok 
Checking for program g++,c++             : /usr/bin/g++ 
Checking for program ar                  : /usr/bin/ar 
Checking for library ['pthread']         : yes 
'configure' finished successfully (0.065s)
Waf: Entering directory `/home/pyro/c++/matching-engine/build'
[ 3/11] cxx: common/src/database/MariaDB_Connector.cpp -> build/common/src/database/MariaDB_Connector.cpp.1.o
../common/src/database/MariaDB_Connector.cpp:13:27: fatal error: my_global.h: No such file or directory
     #include <my_global.h>
                           ^
compilation terminated.
Waf: Leaving directory `/home/pyro/c++/matching-engine/build'
Build failed
 -> task in 'common' failed (exit status 1): 
    {task 140497763739728: cxx MariaDB_Connector.cpp -> MariaDB_Connector.cpp.1.o}
['/usr/bin/g++', '-std=c++11', '-W', '-Wall', '-Wno-unused-local-typedefs', '-ggdb3', '-O0', '-fno-inline', '-fno-omit-frame-pointer', '-I/home/pyro/c++/matching-engine/build/common/include/logger', '-I/home/pyro/c++/matching-engine/common/include/logger', '-I/home/pyro/c++/matching-engine/build/common/include/database', '-I/home/pyro/c++/matching-engine/common/include/database', '-I/home/pyro/c++/matching-engine/build/common/include', '-I/home/pyro/c++/matching-engine/common/include', '-I/home/pyro/c++/matching-engine/build/common/include', '-I/home/pyro/c++/matching-engine/common/include', '-I/export/mariadb/include', '-I/export/boost/105600/include', '-DMARIADB', '-DBOOST', '../common/src/database/MariaDB_Connector.cpp', '-c', '-o', 'common/src/database/MariaDB_Connector.cpp.1.o']
```
